from setuptools import setup, find_packages

setup(
    name="yolo_world",
    version="0.1.0",
    description="YOLO-World: Real-time Open Vocabulary Object Detection",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    keywords="object detection",
    author="Tencent AILab",
    author_email="ronnysong@tencent.com",
    license="Apache License 2.0",
    classifiers=[
        "Development Status :: 4 - Beta",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    python_requires=">=3.7",
    install_requires=[
        "wheel",
        "torch>=1.11.0",
        "torchvision>=0.16.2",
        "transformers",
        "tokenizers",
        "numpy",
        "opencv-python",
        "supervision==0.19.0",
        "openmim",
        "mmcv-lite==2.0.1",
        "mmdet==3.0.0",
        "mmengine>=0.7.1",
        "openmim",
        "mmcv==2.0.1",
        'mmyolo @ git+https://github.com/onuralpszr/mmyolo.git',
    ],
    package_dir={"": "yolo_world"},
    packages=find_packages(where="yolo_world"),
    include_package_data=False,
    zip_safe=True,
    license_files=["LICENSE"],
    exclude_package_data={
        '': ['docs*', 'tests*', 'third_party*', 'assets*'],
    },
)
